[package]
name = "unsafe-libyaml"
version = "0.0.0"
edition = "2021"
publish = false

[workspace]
[dev-dependencies]
pretty_assertions = "1.0"
unsafe-libyaml-test-suite = { path = "tests/data" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
