[package]
name = "unsafe-libyaml"
version = "0.0.0"
edition = "2018"
publish = false

[[test]]
name = "test_reader"
harness = false

[[test]]
name = "test_version"
harness = false

[workspace]
[dev-dependencies]
pretty_assertions = "1.0"
unsafe-libyaml-test-suite = { path = "tests/data" }
